spring:
  application:
    name: PlayView
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: "jdbc:mysql://localhost:3306/play_view?createDatabaseIfNotExist=true"
    username: root
    password: ${MySqlPass}

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      springframework:
        security: DEBUG
    com:
      example:
        play_view: DEBUG
